"""create_agent_runs_and_steps_tables

Revision ID: 71188cf54d80
Revises: 
Create Date: 2025-12-26 15:18:05.890242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71188cf54d80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('error', sa.Text(), nullable=True))
    op.alter_column('agent_runs', 'goal',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='The original goal/request from the user',
               existing_nullable=False)
    op.alter_column('agent_runs', 'workspace_path',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=500),
               comment=None,
               existing_comment='Absolute path to workspace directory for file operations',
               existing_nullable=False)
    op.alter_column('agent_runs', 'plan',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Structured plan generated from goal',
               existing_nullable=True)
    op.drop_column('agent_runs', 'error_message')
    op.drop_column('agent_runs', 'completed_at')
    op.drop_column('agent_runs', 'total_cost')
    op.add_column('agent_steps', sa.Column('error', sa.Text(), nullable=True))
    op.alter_column('agent_steps', 'step_number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Execution order within the run (1, 2, 3...)',
               existing_nullable=False)
    op.alter_column('agent_steps', 'input',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Step-specific input parameters',
               existing_nullable=False)
    op.alter_column('agent_steps', 'output',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Step output after execution',
               existing_nullable=True)
    op.alter_column('agent_steps', 'cost_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Cost details: model, tokens, cost, latency_ms',
               existing_nullable=True)
    op.alter_column('agent_steps', 'prompt_sent',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Exact prompt sent to LLM (for analyze/summarize steps)',
               existing_nullable=True)
    op.alter_column('agent_steps', 'response_received',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Exact response from LLM',
               existing_nullable=True)
    op.drop_column('agent_steps', 'error_message')
    op.drop_column('agent_steps', 'requires_approval')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_steps', sa.Column('requires_approval', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('agent_steps', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('agent_steps', 'response_received',
               existing_type=sa.TEXT(),
               comment='Exact response from LLM',
               existing_nullable=True)
    op.alter_column('agent_steps', 'prompt_sent',
               existing_type=sa.TEXT(),
               comment='Exact prompt sent to LLM (for analyze/summarize steps)',
               existing_nullable=True)
    op.alter_column('agent_steps', 'cost_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Cost details: model, tokens, cost, latency_ms',
               existing_nullable=True)
    op.alter_column('agent_steps', 'output',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Step output after execution',
               existing_nullable=True)
    op.alter_column('agent_steps', 'input',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Step-specific input parameters',
               existing_nullable=False)
    op.alter_column('agent_steps', 'step_number',
               existing_type=sa.INTEGER(),
               comment='Execution order within the run (1, 2, 3...)',
               existing_nullable=False)
    op.drop_column('agent_steps', 'error')
    op.add_column('agent_runs', sa.Column('total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Total cost in USD for all LLM calls in this run'))
    op.add_column('agent_runs', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('agent_runs', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('agent_runs', 'plan',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Structured plan generated from goal',
               existing_nullable=True)
    op.alter_column('agent_runs', 'workspace_path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=1024),
               comment='Absolute path to workspace directory for file operations',
               existing_nullable=False)
    op.alter_column('agent_runs', 'goal',
               existing_type=sa.TEXT(),
               comment='The original goal/request from the user',
               existing_nullable=False)
    op.drop_column('agent_runs', 'error')
    # ### end Alembic commands ###
